### ISSUE TITLE
Setting boolean options as `false` sets them as `true`

### ISSUE THREAD

**Issue by pepkin88** [smsapi/smsapi-javascript-client#4]
Example:
```js
smsapi.message.sms()
    .from('Info')
    .to('501501501')
    .message('My message')
    .normalize(false)
    .execute()
```
Calling `.normalize(false)` will actually result in setting the `normalize` option to `true`. I presume this is because it is probably sent to the server as `normalize=false` which is not `normalize=0` and therefore is interpreted as setting the option.

The use case:
```js
var message = 'Pewna wiadomość'
return smsapi.message.sms()
    .from('Info')
    .to('501501501')
    .message(message)
    .normalize(message.length > 70)
    .execute()
```
Temporary fix: coercing to number like this: `.normalize(+(message.length > 70))`.

**Comment by tymekpudlik** [comment]
Hi @pepkin88. Thank you for informing us about this bug. I believe it is fixed in this [commit](https://github.com/smsapi/smsapi-javascript-client/commit/0bac756aedac5981867310bf56215195eae17a94). I bumped version on NPM to `1.5.7` which includes this fix. You can find it [here](https://www.npmjs.com/package/smsapi) or just update library in your project.

Let me know if your issue is resolved now :)

**Comment by pepkin88** [comment]
Yes, the issue is resolved.
